package com.socks.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.socks.greendao.JokeCache;

import com.socks.greendao.JokeCacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig jokeCacheDaoConfig;

    private final JokeCacheDao jokeCacheDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        jokeCacheDaoConfig = daoConfigMap.get(JokeCacheDao.class).clone();
        jokeCacheDaoConfig.initIdentityScope(type);

        jokeCacheDao = new JokeCacheDao(jokeCacheDaoConfig, this);

        registerDao(JokeCache.class, jokeCacheDao);
    }
    
    public void clear() {
        jokeCacheDaoConfig.getIdentityScope().clear();
    }

    public JokeCacheDao getJokeCacheDao() {
        return jokeCacheDao;
    }

}
